apiVersion : apps/v1
kind: Deployment
metadata:
  name: "mvcappcluster-345a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "mvcappcluster-345a"
  template:
    metadata:
      labels:
        app: "mvcappcluster-345a"
    spec:
      containers:
        - name: "mvcappcluster-345a"
          image: "mvcappcontainer.azurecr.io/mvcappcluster"
          ports:
          - containerPort: 80