on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n mvcappcontainer -g mvcappcontainera1dd-rg --location "East US 2" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n mvcappcontainer --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n mvcappcontainer --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n mvcappcontainer --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: mvcappcontainer.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t mvcappcontainer.azurecr.io/mvcappcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push mvcappcontainer.azurecr.io/mvcappcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_mvcappcluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mvc-app-cluster8f28 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mvc-app-cluster8f28`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mvc-app-cluster8f28
        container-registry-url: mvcappcontainer.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: mvcappclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mvc-app-cluster8f28
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          mvcappcontainer.azurecr.io/mvcappcluster:${{ github.sha }}
        imagepullsecrets: |
          mvcappclustedockerauth   
